version: '3.8'
services:
  
  ### Prometheus ###
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  
  ### Grafana ###
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_SERVER_HTTP_PORT=8080
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

volumes:
  prom_data:
    driver: local

networks:
  default:
    driver: bridge