# enabled modules for monitoring (e.g. application, mysql, etc)

metricbeat.modules:

#------------------------------- Prometheus Application Metrics Module -------------------------------
- module: prometheus
  enabled: true
  period: 10s
  metricsets: ["collector"]
  hosts: ["host.docker.internal:3000"]
  metrics_path: /metrics

# - module: prometheus
#   enabled: true
#   period: 30s
#   metricsets: ["collector"]
#   hosts: ["host.docker.internal:3005"]
#   metrics_path: /metrics

#------------------------------- Elasticsearch Module -------------------------------
# - module: elasticsearch
#   enabled: true
#   xpack.enabled: true
#   period: 10s
#   hosts: ["localhost:9200"]

#------------------------------- RabbitMQ Module -------------------------------
# - module: rabbitmq
#   enabled: true
#   metricsets: ["node"]
#   period: 5s
#   hosts: ["rabbitmq:15672"]
#   username: guest
#   password: guest

#------------------------------- MongoDB Module -------------------------------
# - module: mongodb
#   enabled: true
#   metricsets: ["status", "dbstats"]
#   period: 5s
#   hosts: ["mongodb:27017"]

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  username: "elastic"
  password: "changeme"
  hosts: ["${HOST_ELASTICSEARCH}"]

setup.kibana:
  host: "${HOST_KIBANA}"

#============================== Dashboards =====================================
# These settings control loading the sample dashboards to the Kibana index. Loading
# the dashboards is disabled by default and can be enabled either by setting the
# options here, or by using the `-setup` CLI flag.
setup.dashboards.enabled: true

logging.level: warning
logging.to_files: true
logging.to_syslog: false
logging.files:
  path: /var/log/metricbeat
  name: metricbeat.log
  keepfiles: 2
  permissions: 0644
